name: Build & Release

on:
  push:
    tags:
      - "v*"    

permissions:
  contents: write
  
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install pyinstaller pywebview pypdf

      - name: Build exe
        run: |
          pyinstaller app.py --add-data "index.html;." --noconsole --onefile --name "z-merge" --icon="icon.ico"

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/z-merge.exe

  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install pyinstaller pywebview pypdf pyobjc-framework-WebKit

      - name: Build app
        run: |
          pyinstaller app.py --add-data "index.html:." --noconsole --onefile --name "z-merge"

      - name: Zip it
        run: zip -r "z-merge Mac.zip" "dist/z-merge"

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          files: "z-merge Mac.zip"